SUPABASE_URL_OLD = "postgresql://postgres.xhmndscsnqvaxanxrdwd:dataaiproject1!28@aws-0-us-east-1.pooler.supabase.com:5432/postgres"

DATABASE_URL="postgresql://postgres.xhmndscsnqvaxanxrdwd:dataaiproject1!28@aws-1-us-east-1.pooler.supabase.com:6543/postgres?pgbouncer=true"

# Connect to Postgres via the shared session-mode pooler (used for migrations)
SUPABASE_URL="postgresql://postgres.xhmndscsnqvaxanxrdwd:dataaiproject1!28@aws-1-us-east-1.pooler.supabase.com:5432/postgres"

GEMINI_API_KEY = "AIzaSyCnVgR_jpkjEdqeUkEvwFLgMvdYn_Mzra0"